// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\n" +
	"calculator\x1a\tsum.proto\x1a\fprimes.proto\x1a\tavg.proto2\xcc\x01\n" +
	"\x11CalculatorService\x128\n" +
	"\x03Sum\x12\x16.calculator.SumRequest\x1a\x17.calculator.SumResponse\"\x00\x12A\n" +
	"\x06Primes\x12\x18.calculator.PrimeRequest\x1a\x19.calculator.PrimeResponse\"\x000\x01\x12:\n" +
	"\x03Avg\x12\x16.calculator.AvgRequest\x1a\x17.calculator.AvgResponse\"\x00(\x01B0Z.github.com/Omar-Sa6ry/grpc-go/calculator/protob\x06proto3"

var file_calculator_proto_goTypes = []any{
	(*SumRequest)(nil),    // 0: calculator.SumRequest
	(*PrimeRequest)(nil),  // 1: calculator.PrimeRequest
	(*AvgRequest)(nil),    // 2: calculator.AvgRequest
	(*SumResponse)(nil),   // 3: calculator.SumResponse
	(*PrimeResponse)(nil), // 4: calculator.PrimeResponse
	(*AvgResponse)(nil),   // 5: calculator.AvgResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: calculator.CalculatorService.Sum:input_type -> calculator.SumRequest
	1, // 1: calculator.CalculatorService.Primes:input_type -> calculator.PrimeRequest
	2, // 2: calculator.CalculatorService.Avg:input_type -> calculator.AvgRequest
	3, // 3: calculator.CalculatorService.Sum:output_type -> calculator.SumResponse
	4, // 4: calculator.CalculatorService.Primes:output_type -> calculator.PrimeResponse
	5, // 5: calculator.CalculatorService.Avg:output_type -> calculator.AvgResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	file_sum_proto_init()
	file_primes_proto_init()
	file_avg_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
